#---------------- 服务端口-----------------------------
server:
  port: 5081                               #定义服务端口
#----------------------------------------------------
spring:
  profiles:
    active: '@package.environment@'
  application:
    name: objcet-api
    
#--------------日志数据 ------------------------
logging:
  config: classpath:logs/logback-spring.xml
  