eureka: 
  instance: # eureak实例定义
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
    instance-id: objcet-api  # 在信息列表时显示主机名称
    prefer-ip-address: true     # 访问的路径变为IP地址
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://edmin:mldnjava@localhost:7001/eureka/